# Generated by Django 5.1.7 on 2025-04-01 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursecontent_delete_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('course_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_items', to='courses.coursecontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
