# Generated by Django 5.1.7 on 2025-04-01 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecontent',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='table_of_contents',
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PDFSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.IntegerField()),
                ('course_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.coursecontent')),
                ('parent_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='courses.pdfsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
