# Generated by Django 5.1.7 on 2025-04-01 17:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_updated_at_coursecontent_last_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecontent',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='sections',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='PDFSection',
        ),
    ]
