# Generated by Django 5.1.7 on 2025-04-01 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_last_updated_coursecontent_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='_original_file_name',
            field=models.CharField(blank=True, editable=False, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video')], default='video', max_length=50),
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='CourseContent',
        ),
    ]
