# Generated by Django 5.1.7 on 2025-04-01 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course__original_file_name_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='_original_file_name',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='course',
        ),
        migrations.CreateModel(
            name='CoursePdfInternal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512)),
                ('table_of_contents', models.JSONField(blank=True, default=list)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_internal_data', to='courses.course')),
            ],
        ),
        migrations.AddField(
            model_name='coursesection',
            name='pdf_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.coursepdfinternal'),
        ),
    ]
