# Generated by Django 5.1.7 on 2025-04-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_course__original_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='file_type',
        ),
        migrations.AddField(
            model_name='course',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='courses/pdfs/', verbose_name='PDF Document'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='courses/videos/', verbose_name='Video File'),
        ),
    ]
