# Generated by Django 5.1.7 on 2025-04-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_course_file_type_course_pdf_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='file',
        ),
    ]
