# Generated by Django 5.1.7 on 2025-04-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_course_pdf_file_remove_course_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='file',
        ),
        migrations.AddField(
            model_name='course',
            name='pdfs',
            field=models.FileField(blank=True, null=True, upload_to='courses/pdfs/', verbose_name='PDF Document'),
        ),
        migrations.AddField(
            model_name='course',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='courses/videos/', verbose_name='Video File'),
        ),
    ]
