# Generated by Django 5.1.7 on 2025-04-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_course_file_course_pdfs_course_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quize',
            field=models.FileField(blank=True, null=True, upload_to='courses/quizes/', verbose_name='Quizes Document'),
        ),
    ]
