# Generated by Django 5.1.7 on 2025-04-07 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_course_quize_course_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='answer',
            new_name='quizzes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='course',
            name='question',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
