# Generated by Django 5.1.7 on 2025-04-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_remove_quiz_course_course_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='course',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='course',
            name='question',
        ),
        migrations.RemoveField(
            model_name='course',
            name='quizzes',
        ),
    ]
